version: '3'

networks:
  ics:
    driver: bridge

services:

  scadalts:
    image: kamiljarmusik/scadalts-2.6.18-mysql-8
    ports:
      - "8080:8080"
    env_file: ./database/db.env
    expose: [ "8080", "8000" ]
    networks:
      - ics

  openplc:
    image: sflorenz05/open-plc:v0.1
    depends_on:
      - scadalts
    ports:
      - "502:502"
      - "8081:8080"
    command: -privileged
    networks:
      - ics

  matlab:
    image: sflorenz05/matlab_simulink:v0.3
    shm_size: 512M
    ports:
      - "5901:5901"
      - "6080:6080"
    environment:
      PASSWORD: "ILoveMATLAB"
    command: -vnc
    volumes:
      - ../../simulink:/home/matlab/Documents/MATLAB/simulink
    networks:
      - ics
