version: '3'

networks:
  ics:
    driver: bridge

services:

  database:
    container_name: mysql
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=scadalts
    expose: [ "3306" ]
    volumes:
      - ../mysql/databases:/var/lib/mysql
    networks:
      - ics

  scadalts:
    image: scadalts/scadalts:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    expose: [ "8080", "8000" ]
    links:
      - database:database
    networks:
      - ics

  openplc:
    image: sflorenz05/open-plc
    depends_on:
      - scadalts
    ports:
      - "502:502"
      - "8081:8080"
    volumen:
      - ../openplc:/home/openplc/scripts
    networks:
      - ics
  ####

#  matlab:
#    image: mathworks/matlab:r2021b
#    shm_size: 512M
#    ports:
#      - "5901:5901"
#      - "6080:6080"
#    environment:
#      PASSWORD: "ILoveMATLAB"
#      command: -vnc
#      volumes:
#      - ../matlab/simulink:/home/matlab/Documents/MATLAB/simulink
