version: '3'

networks:
  icsnetwork_ics:
    external: true

services:
  modtester:
    image: sflorenz05/modtester:v0.2
    working_dir: /modtester
    volumes:
      - ../../modtester:/modtester
    command: tail -F anything
    networks:
      - icsnetwork_ics
